#! /bin/bash
#
# finddirs 1.0.1, 2023-02-23
#
# Findet die Verzeichnisse, in denen Fonts, ttf-Dateien liegen oder
# alternativ, wenn eine Dateiendung angegeben wird alle Verzeichnisse
# mit Dateien, die so enden.
#
# Das Script ist abhängig von locate, dessen Datenbank nicht automatisch
# immer auf dem neuesten Stand ist. Für garantiert aktuelle Ergebnisse muss
# also vorher das Kommando updatedb gegeben werden. Um aber das Script nicht
# unnoetig zu verlangsamen, habe ich dieses Kommando nicht in dieses Script
# integriert.
#
# Bernd Storck, https://www.facebook.com/BStLinux/
#

exitval=1  ## Misslingen ist Default.

[ -n "$1" ] && extension="$1" || extension="ttf"

temp_file="dirs1_$extension"
target_file="dirs_$extension"

rm --force "$temp_file"
locate -br "^.*\.$extension$" | xargs -I'{}' dirname '{}' >> "$temp_file"

rm --force "$target_file"
if [ -s "$temp_file" ]; then
#  sort "$temp_file" | uniq >> "$target_file"
#  if [ "$?" = 0 ]; then
  if sort "$temp_file" | uniq >> "$target_file"; then
    rm -f "$temp_file"
    exitval=0
  fi
fi

if [ -s "$target_file" ]; then
  less "$target_file" 2> /dev/null
fi
ls -gotrh | cut -d' ' -f3-

exit "$exitval"
